/**
 * @File Name          : helloWorld.cls
 * @Description        : 
 * @Author             : Nilesh Patil
 * @Group              : 
 * @Last Modified By   : Nilesh Patil
 * @Last Modified On   : 26/6/2020, 6:48:25 pm
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    23/6/2020   Nilesh Patil     Initial Version
**/
public class helloWorld {
    
      public static string sendMessage(String name){
          return 'Hello DevOps Nilesh demo 2' + name;
          
      }


}